# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: provaicetec
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: provaicetec
  adminer:
    container_name: mysqladmin
    image: adminer
    restart: always
    ports:
      - 8082:8080